# Generated by Django 3.0.6 on 2020-05-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='date_poster',
            new_name='date_posted',
        ),
    ]
